name: flutter_foodninja_bloc_tdd_clean_arc

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.4
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.2


dev_dependencies:
  bloc_test: ^9.1.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          style: italic 
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400

    - family: BentonSans
      fonts:
        - asset: assets/fonts/BentonSans/BentonSans-Bold.otf
          weight: 700
        - asset: assets/fonts/BentonSans/BentonSans-Light.otf
          weight: 300
        - asset: assets/fonts/BentonSans/BentonSans-Regular.otf
          weight: 400
        - asset: assets/fonts/BentonSans/BentonSans-Thin.otf
          weight: 200 
